spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ticket_workflow;MODE=LEGACY;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=VALUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.flowable: info
    com.example.ticketworkflow: info
