spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ticket_workflow
    username: postgres
    password: postgres

logging:
  level:
    org.flowable: info
    com.example.ticketworkflow: info
