-- ============================================
-- 工单处理系统 PostgreSQL 16 建表脚本
-- ============================================

create table if not exists sys_user (
    user_id bigint generated by default as identity primary key,
    username varchar(64) not null,
    display_name varchar(64) not null,
    user_type varchar(16) not null,
    external_user_flag smallint not null default 0,
    phone varchar(32),
    email varchar(128),
    status varchar(16) not null default 'ENABLED',
    sso_subject varchar(128),
    last_login_at timestamp,
    remark varchar(255),
    deleted_flag smallint not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_sys_user_username unique (username)
);

create table if not exists sys_role (
    role_id bigint generated by default as identity primary key,
    role_code varchar(64) not null,
    role_name varchar(64) not null,
    data_scope varchar(32) not null,
    status varchar(16) not null default 'ENABLED',
    remark varchar(255),
    deleted_flag smallint not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_sys_role_role_code unique (role_code)
);

create table if not exists sys_menu (
    menu_id bigint generated by default as identity primary key,
    parent_id bigint not null default 0,
    menu_name varchar(64) not null,
    menu_type varchar(16) not null,
    route_path varchar(128),
    component_path varchar(255),
    permission_code varchar(128),
    icon varchar(64),
    sort_order integer not null default 0,
    visible_flag smallint not null default 1,
    enabled_flag smallint not null default 1,
    keep_alive_flag smallint not null default 0,
    remark varchar(255),
    deleted_flag smallint not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create unique index if not exists uk_sys_menu_permission_code
    on sys_menu(permission_code)
    where permission_code is not null;

create table if not exists sys_user_role (
    user_role_id bigint generated by default as identity primary key,
    user_id bigint not null,
    role_id bigint not null,
    created_at timestamp not null default current_timestamp,
    constraint uk_sys_user_role unique (user_id, role_id),
    constraint fk_sys_user_role_user_id foreign key (user_id) references sys_user(user_id),
    constraint fk_sys_user_role_role_id foreign key (role_id) references sys_role(role_id)
);

create table if not exists sys_role_menu (
    role_menu_id bigint generated by default as identity primary key,
    role_id bigint not null,
    menu_id bigint not null,
    created_at timestamp not null default current_timestamp,
    constraint uk_sys_role_menu unique (role_id, menu_id),
    constraint fk_sys_role_menu_role_id foreign key (role_id) references sys_role(role_id),
    constraint fk_sys_role_menu_menu_id foreign key (menu_id) references sys_menu(menu_id)
);

create table if not exists biz_handle_group (
    handle_group_id bigint generated by default as identity primary key,
    group_code varchar(64) not null,
    group_name varchar(64) not null,
    group_type varchar(32) not null,
    leader_user_id bigint,
    leader_name varchar(64),
    status varchar(16) not null default 'ENABLED',
    remark varchar(255),
    deleted_flag smallint not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_biz_handle_group_group_code unique (group_code)
);

create table if not exists biz_handle_group_member (
    group_member_id bigint generated by default as identity primary key,
    handle_group_id bigint not null,
    user_id bigint not null,
    leader_flag smallint not null default 0,
    primary_group_flag smallint not null default 1,
    created_at timestamp not null default current_timestamp,
    constraint uk_biz_handle_group_member unique (handle_group_id, user_id),
    constraint fk_biz_handle_group_member_group_id foreign key (handle_group_id) references biz_handle_group(handle_group_id),
    constraint fk_biz_handle_group_member_user_id foreign key (user_id) references sys_user(user_id)
);

create table if not exists sys_dict_type (
    dict_type_id bigint generated by default as identity primary key,
    dict_type_code varchar(64) not null,
    dict_type_name varchar(64) not null,
    status varchar(16) not null default 'ENABLED',
    remark varchar(255),
    deleted_flag smallint not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_sys_dict_type_code unique (dict_type_code)
);

create table if not exists sys_dict_item (
    dict_item_id bigint generated by default as identity primary key,
    dict_type_id bigint not null,
    item_code varchar(64) not null,
    item_name varchar(64) not null,
    item_value varchar(128) not null,
    sort_order integer not null default 0,
    status varchar(16) not null default 'ENABLED',
    deleted_flag smallint not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_sys_dict_item unique (dict_type_id, item_code),
    constraint fk_sys_dict_item_type_id foreign key (dict_type_id) references sys_dict_type(dict_type_id)
);

create table if not exists ticket_sla_rule (
    sla_rule_id bigint generated by default as identity primary key,
    priority_code varchar(16) not null,
    response_limit_minutes integer not null,
    resolve_limit_minutes integer not null,
    enabled_flag smallint not null default 1,
    remark varchar(255),
    deleted_flag smallint not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_ticket_sla_rule_priority_code unique (priority_code)
);

create table if not exists ticket_order (
    ticket_id bigint generated by default as identity primary key,
    ticket_no varchar(64) not null,
    title varchar(255) not null,
    description text not null,
    requester_user_id bigint not null,
    requester_name varchar(64) not null,
    contact_phone varchar(32),
    external_user_flag smallint not null default 0,
    source_code varchar(32) not null,
    ticket_type_code varchar(32) not null,
    category_code varchar(32) not null,
    priority_code varchar(16) not null,
    current_status varchar(32) not null,
    current_handler_user_id bigint,
    current_handle_group_id bigint,
    escalated_flag smallint not null default 0,
    escalate_reason varchar(500),
    escalate_time timestamp,
    escalate_operator_id bigint,
    timeout_flag smallint not null default 0,
    response_timeout_flag smallint not null default 0,
    resolve_timeout_flag smallint not null default 0,
    response_warn_notified_flag smallint not null default 0,
    resolve_warn_notified_flag smallint not null default 0,
    response_sla_minutes integer not null,
    resolve_sla_minutes integer not null,
    response_deadline timestamp not null,
    resolve_deadline timestamp not null,
    response_finished_at timestamp,
    resolve_finished_at timestamp,
    accepted_at timestamp,
    assigned_at timestamp,
    processed_at timestamp,
    user_confirmed_at timestamp,
    closed_at timestamp,
    suspend_reason varchar(500),
    close_reason varchar(500),
    reopen_reason varchar(500),
    resolution_summary varchar(1000),
    reopen_count integer not null default 0,
    version integer not null default 0,
    deleted_flag smallint not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_ticket_order_ticket_no unique (ticket_no),
    constraint fk_ticket_order_requester_user_id foreign key (requester_user_id) references sys_user(user_id),
    constraint fk_ticket_order_current_handler_user_id foreign key (current_handler_user_id) references sys_user(user_id),
    constraint fk_ticket_order_current_handle_group_id foreign key (current_handle_group_id) references biz_handle_group(handle_group_id),
    constraint fk_ticket_order_escalate_operator_id foreign key (escalate_operator_id) references sys_user(user_id)
);

create table if not exists ticket_flow_record (
    flow_record_id bigint generated by default as identity primary key,
    ticket_id bigint not null,
    action_code varchar(32) not null,
    from_status varchar(32),
    to_status varchar(32),
    operator_user_id bigint not null,
    operator_name varchar(64) not null,
    operate_description varchar(1000) not null,
    operate_time timestamp not null default current_timestamp,
    request_path varchar(255),
    deleted_flag smallint not null default 0,
    constraint fk_ticket_flow_record_ticket_id foreign key (ticket_id) references ticket_order(ticket_id),
    constraint fk_ticket_flow_record_operator_user_id foreign key (operator_user_id) references sys_user(user_id)
);

create table if not exists ticket_attachment (
    attachment_id bigint generated by default as identity primary key,
    ticket_id bigint not null,
    original_file_name varchar(255) not null,
    storage_file_name varchar(255) not null,
    storage_path varchar(500) not null,
    file_extension varchar(32),
    file_size bigint not null,
    uploader_user_id bigint not null,
    uploader_name varchar(64) not null,
    created_at timestamp not null default current_timestamp,
    deleted_flag smallint not null default 0,
    constraint fk_ticket_attachment_ticket_id foreign key (ticket_id) references ticket_order(ticket_id),
    constraint fk_ticket_attachment_uploader_user_id foreign key (uploader_user_id) references sys_user(user_id)
);

create table if not exists sys_notice (
    notice_id bigint generated by default as identity primary key,
    receiver_user_id bigint not null,
    notice_title varchar(128) not null,
    notice_content varchar(1000) not null,
    notice_type varchar(32) not null,
    business_type varchar(32),
    business_id bigint,
    read_flag smallint not null default 0,
    read_time timestamp,
    created_at timestamp not null default current_timestamp,
    deleted_flag smallint not null default 0,
    constraint fk_sys_notice_receiver_user_id foreign key (receiver_user_id) references sys_user(user_id)
);

create table if not exists sys_audit_log (
    audit_log_id bigint generated by default as identity primary key,
    operator_user_id bigint,
    operator_name varchar(64) not null,
    module_name varchar(64) not null,
    operation_type varchar(64) not null,
    business_id bigint,
    operation_description varchar(1000) not null,
    request_path varchar(255),
    request_ip varchar(64),
    created_at timestamp not null default current_timestamp
);

create index if not exists idx_sys_user_status on sys_user(status);
create index if not exists idx_sys_menu_parent_id on sys_menu(parent_id);
create index if not exists idx_ticket_order_requester_user_id on ticket_order(requester_user_id);
create index if not exists idx_ticket_order_current_status on ticket_order(current_status);
create index if not exists idx_ticket_order_priority_code on ticket_order(priority_code);
create index if not exists idx_ticket_order_current_handler_user_id on ticket_order(current_handler_user_id);
create index if not exists idx_ticket_order_current_handle_group_id on ticket_order(current_handle_group_id);
create index if not exists idx_ticket_order_created_at on ticket_order(created_at desc);
create index if not exists idx_ticket_order_timeout_flag on ticket_order(timeout_flag);
create index if not exists idx_ticket_flow_record_ticket_id on ticket_flow_record(ticket_id);
create index if not exists idx_ticket_attachment_ticket_id on ticket_attachment(ticket_id);
create index if not exists idx_sys_notice_receiver_user_id on sys_notice(receiver_user_id);
create index if not exists idx_sys_audit_log_operator_user_id on sys_audit_log(operator_user_id);
create index if not exists idx_sys_audit_log_created_at on sys_audit_log(created_at desc);
