CREATE TABLE IF NOT EXISTS form_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512),
    status VARCHAR(32) NOT NULL,
    schema_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS node_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    node_state VARCHAR(32) NOT NULL,
    form_id BIGINT NOT NULL,
    assignee VARCHAR(64) NOT NULL,
    action_type VARCHAR(32) NOT NULL,
    description VARCHAR(512),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS flow_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flow_code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512),
    status VARCHAR(32) NOT NULL,
    start_node_id BIGINT NOT NULL,
    graph_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS flow_transition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flow_id BIGINT NOT NULL,
    from_node_id BIGINT NOT NULL,
    to_node_id BIGINT NOT NULL,
    transition_name VARCHAR(128),
    sort_no INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ticket_instance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_no VARCHAR(64) NOT NULL UNIQUE,
    flow_id BIGINT NOT NULL,
    flow_name VARCHAR(128) NOT NULL,
    title VARCHAR(255) NOT NULL,
    applicant VARCHAR(64) NOT NULL,
    current_node_id BIGINT,
    current_node_name VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    business_data_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ticket_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    flow_id BIGINT NOT NULL,
    node_id BIGINT NOT NULL,
    node_name VARCHAR(128) NOT NULL,
    node_state VARCHAR(32) NOT NULL,
    form_id BIGINT NOT NULL,
    assignee VARCHAR(64) NOT NULL,
    action_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ticket_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    node_id BIGINT NOT NULL,
    node_name VARCHAR(128) NOT NULL,
    node_state VARCHAR(32) NOT NULL,
    assignee VARCHAR(64) NOT NULL,
    operator VARCHAR(64) NOT NULL,
    action_type VARCHAR(32) NOT NULL,
    comment VARCHAR(1000),
    selected_next_node_id BIGINT,
    selected_next_node_name VARCHAR(128),
    submitted_data_json TEXT NOT NULL,
    merged_data_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_transition_flow_id ON flow_transition (flow_id);
CREATE INDEX IF NOT EXISTS idx_ticket_instance_flow_id ON ticket_instance (flow_id);
CREATE INDEX IF NOT EXISTS idx_ticket_instance_status ON ticket_instance (status);
CREATE INDEX IF NOT EXISTS idx_ticket_task_ticket_id ON ticket_task (ticket_id);
CREATE INDEX IF NOT EXISTS idx_ticket_task_assignee_status ON ticket_task (assignee, status);
CREATE INDEX IF NOT EXISTS idx_ticket_record_ticket_id ON ticket_record (ticket_id);
