CREATE TABLE IF NOT EXISTS wf_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(1000),
    status VARCHAR(32) NOT NULL,
    version_no INTEGER NOT NULL,
    process_definition_key VARCHAR(128) NOT NULL,
    process_definition_id VARCHAR(128),
    bpmn_xml TEXT NOT NULL,
    definition_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS wf_ticket_instance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_key VARCHAR(64) NOT NULL UNIQUE,
    template_id BIGINT NOT NULL,
    template_code VARCHAR(64) NOT NULL,
    template_name VARCHAR(128) NOT NULL,
    process_definition_id VARCHAR(128) NOT NULL,
    process_instance_id VARCHAR(128) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    initiator VARCHAR(64) NOT NULL,
    current_node_key VARCHAR(128),
    current_node_name VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    merged_form_data TEXT NOT NULL,
    searchable_text TEXT,
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS wf_ticket_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id BIGINT NOT NULL,
    process_instance_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128),
    task_definition_key VARCHAR(128),
    task_name VARCHAR(128),
    assignee VARCHAR(64),
    operator VARCHAR(64) NOT NULL,
    action VARCHAR(32) NOT NULL,
    comment VARCHAR(1000),
    submitted_form_data TEXT NOT NULL,
    merged_form_data TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS wf_ticket_field_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id BIGINT NOT NULL,
    field_key VARCHAR(128) NOT NULL,
    field_label VARCHAR(128),
    field_value VARCHAR(2000),
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_wf_instance_status ON wf_ticket_instance (status);
CREATE INDEX IF NOT EXISTS idx_wf_instance_template_id ON wf_ticket_instance (template_id);
CREATE INDEX IF NOT EXISTS idx_wf_instance_initiator ON wf_ticket_instance (initiator);
CREATE INDEX IF NOT EXISTS idx_wf_record_instance_id ON wf_ticket_record (instance_id);
CREATE INDEX IF NOT EXISTS idx_wf_field_index_instance_id ON wf_ticket_field_index (instance_id);
CREATE INDEX IF NOT EXISTS idx_wf_field_index_key_value ON wf_ticket_field_index (field_key, field_value);
